### ISSUE TITLE
Couldn't find file 'jquery.selectric' with type 'application/javascript'

### ISSUE THREAD

**Issue by PickRelated** [malagant/jquery-selectric-rails#1]
Hello!
I had some problem installing this gem. I had to specify git path because when I point out jquery-selectric-rails in gemfile, I get dependency error because I use Rails 4, not 3.2.
Anyway your gemspec files does not contain `jquery-selectric-rails`, it contains `js-selectric-rails` instead.
So in my Gemfile I wrote a string
`gem 'js-selectric-rails', github: 'malagant/jquery-selectric-rails'`
`bundle install` command succeeded and shows
`Using js-selectric-rails 1.9.3 from git://github.com/malagant/jquery-selectric-rails.git (at master)`
In application.js I wrote a string
`//= require jquery.selectric`
But now I get `couldn't find file 'jquery.selectric' with type 'application/javascript'` rails error.
I also do not see this gem in gem paths.
I see a star for your repo which means someone got it working. What am I doing wrong?
Thanks!

**Comment by malagant** [comment]
Hi Igor,

I’m nearly sure that you did a „bundle install“ and restarted your server. ;)
I have tried the gem and it didn’t produce any problem.

Please use the gem name from the Readme jquery-selectric-rails.

bundle install 
restart server

and you should be fine. If not, please don’t hesitate to contact me again.

Regards

Michael

Von:  Igor Tatarintsev
Antworten an:  malagant/jquery-selectric-rails
Datum:  Samstag, 10. Oktober 2015 um 13:30
An:  malagant/jquery-selectric-rails
Betreff:  [jquery-selectric-rails] Couldn't find file 'jquery.selectric' with type 'application/javascript' (#1)

Hello!
I had some problem installing this gem. I had to specify git path, but also your gemspec files does not contain jquery-selectric-rails, it contains js-selectric-rails instead.
So in my Gemfile I wrote a string
gem 'js-selectric-rails', github: 'malagant/jquery-selectric-rails'
In application.js I wrote a string
//= require jquery.selectric
But now I get couldn't find file 'jquery.selectric' with type 'application/javascript' rails error.
I see a star for your repo which means someone got it working. What am I doing wrong?
Thanks!

**Comment by PickRelated** [comment]
Thanks for your reply!
When I specify `jquery-selectric-rails` in Gemfile and do `bundle install` I get an error.

```
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (4.2.4)

  In Gemfile:
    jquery-selectric-rails (>= 0) ruby depends on
      railties (> 3.2, ~> 3.2) ruby
```

Can you confirm it works in Rails 4? Or may be you use Rails 3?

**Comment by malagant** [comment]
Yes, i built it for a project, that is running with rails 3.2.

I didn’t test it for rails 4, but i guess, if I update the dependencies, it will work also for rails 4.

Let me see, if I can update it and then I’ll let you know.

Cheers
Michael

Von:  Igor Tatarintsev
Antworten an:  malagant/jquery-selectric-rails
Datum:  Samstag, 10. Oktober 2015 um 17:34
An:  malagant/jquery-selectric-rails
Cc:  Michael Johann
Betreff:  Re: [jquery-selectric-rails] Couldn't find file 'jquery.selectric' with type 'application/javascript' (#1)

Thanks for your reply!
When I specify jquery-selectric-rails in Gemfile and do bundle install I get an error.
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (4.2.4)

  In Gemfile:
    jquery-selectric-rails (>= 0) ruby depends on
      railties (> 3.2, ~> 3.2) ruby
Can you confirm it works in Rails 4? Or may be you use Rails 3?

**Comment by PickRelated** [comment]
That would be super cool! Thanks!

**Comment by malagant** [comment]
Done.
You should now find version 1.9.3.1 which runs with rails 4 also.

Cheers
Michael

Von:  Igor Tatarintsev
Antworten an:  malagant/jquery-selectric-rails
Datum:  Samstag, 10. Oktober 2015 um 17:40
An:  malagant/jquery-selectric-rails
Cc:  Michael Johann
Betreff:  Re: [jquery-selectric-rails] Couldn't find file 'jquery.selectric' with type 'application/javascript' (#1)

That would be super cool! Thanks!

**Comment by PickRelated** [comment]
Awesome! Thank you very much!
The only problem I had is that rails is not sure what file to include.
In application.sass I wrote:
`@include 'jquery.selectric'`
And Rails gave me an error

```
It's not clear which file to import for '@import "jquery.selectric"'.
Candidates:
  jquery.selectric.css
  jquery.selectric.css.scss
```

But when I specified `@include 'jquery.selectric.css'` everything went fine.
