### ISSUE TITLE
Rails 4 does not work with jquery.selectric.css and jquery.selectric.css.scss in place

### ISSUE THREAD

**Issue by slowjack2k** [malagant/jquery-selectric-rails#2]
Rails 4 complains with:

> It's not clear which file to import for '@import "jquery.selectric"'. Candidates: jquery.selectric.css jquery.selectric.css.scss Please delete or rename all but one of these files. 

Can you please fix it?

Regards
Dieter

**Comment by malagant** [comment]
Thanks for sharing. Fixed in 1.9.3.2
